import json
import os

langs = ['pt', 'en', 'es', 'fr']
base_path = r'c:\Users\ryanl\OneDrive\Desktop\aplicativo\translations'

translations = {
    "pt": {
        "tutorial.inicio.title": "Guia: Início",
        "tutorial.inicio.content": "# 🏠 Início\n\n### 🎯 Descrição\nA tela de **Início** é o seu painel central de comando. Ela reúne todas as informações cruciais sobre a execução do jogo e os módulos principais em uma única visão unificada. Ideal para checar rapidamente o status sem perder o foco no que importa.\n\n### ⚙️ Modo de Uso\n1. **Visualizar o Status:** O painel superior mostra de forma clara se o *Foxhole* está aberto e há quanto tempo está sendo executado.\n2. **Chat Integrado:** Converse ao vivo com outros jogadores usando as abas inferiores. Você pode navegar entre os chats de *Logística*, *Faci*, ou o *Global*. O campo de texto suporta emojis automáticos!\n3. **Menu Lateral:** Clique no ícone `☰` no canto superior esquerdo para acessar instantaneamente todas as demais ferramentas de automação e busca.\n\n### 💡 Dicas Importantes\n* Verifique sempre se sua aba de status aponta **\"Usuário Ativo\"** para garantir que você esteja devidamente logado via Steam.\n* Utilize o atalho rápido nos cards inferiores para abrir rapidamente o Stockpile ou a Calculadora de Produção.\n",
        "tutorial.chat.title": "Guia: Chat",
        "tutorial.chat.content": "# Chat\n\n### Descrição\nUse o chat integrado para acompanhar salas da coalizão, ver jogadores online, enviar emojis rápidos ou links de GIF, e receber alertas de menção enquanto usa outras ferramentas.\n\n### Como usar\n1. Conecte com seu perfil Steam local.\n2. Escolha uma sala na lista.\n3. Digite uma mensagem, use emojis rápidos, ou envie uma URL de GIF.\n4. Digite `@` para mencionar usuários online pela barra de sugestões.\n\n### Dicas\n* Overlays e sons de menção podem ser ajustados em Configurações ou Notificações.\n* Previews de GIF aparecem direto na lista quando a URL aponta para uma imagem.",
        "tutorial.ferramentas.title": "Guia: Auto Clicker",
        "tutorial.ferramentas.content": "# Auto Clicker\n\n### Visão geral\nEsta tela controla as automações principais do Foxhole. Use Capturar Foxhole com o jogo aberto para registrar a janela e o ponto virtual onde os cliques serão enviados. Os modos foram feitos para funcionar em segundo plano sempre que possível, sem roubar o foco do jogo.\n\n### Modos\n* Auto Clicker: usa a hotkey principal, por padrão F3, para clicar no botão escolhido a cada 0.3s.\n* Segurar Shift: quando ligado, o Auto Clicker só envia Shift junto se você estiver segurando Shift fisicamente.\n* W Hold: usa a hotkey do piloto, por padrão F4, para segurar W. Segurar S pausa W; soltar S retoma. Esc ou a própria hotkey para o modo.\n* W duplo-toque: quando ligado, dois toques rápidos em W iniciam o W Hold.\n* Move-Click F2: segura o botão esquerdo do mouse no ponto capturado em segundo plano. Use F2 de novo ou Esc para soltar.\n* Right Hold: por padrão F9, segura o botão direito do mouse em segundo plano. Use F9 de novo ou Esc para soltar.\n* Duplo clique direito: vem desligado por padrão; quando ligado, dois cliques direitos rápidos iniciam o Right Hold.\n* Artilharia: por padrão F7, envia R e clique esquerdo em ritmo constante. Esc ou clique direito para parar.\n* Double fixo: usa a tecla configurada para cliques rápidos e permite slots 1 a 4.\n\n### Overlay\nO overlay mostra somente o modo ativo, uma dica curta e os itens habilitados nas configurações. Você pode ativar perfil, alvo, notificação e trocar cor. O painel aparece também enquanto F2, W Hold ou Right Hold estiverem ativos.\n\n### Dicas\n* Capture o Foxhole novamente se o jogo reiniciar ou se o clique estiver indo para o lugar errado.\n* Evite usar a mesma tecla para dois modos.\n* Se um modo parecer preso, pressione Esc para soltar todos os holds ativos.",
        "tutorial.configuracoes.title": "Guia: Configurações",
        "tutorial.configuracoes.content": "# ⚙️ Configurações\n\n### 🎯 Descrição\nPersonalize a experiência do **GG Coalition** com ajustes finos no aplicativo e nas notificações sobre a tela (Overlay). Deixe tudo com a sua cara e com as cores que preferir.\n\n### ⚙️ Modo de Uso\n* **Efeitos Sonoros:** Ative ou desative o bip que toca quando um timer se encerra ou quando alguém te menciona no chat.\n* **Sistema (Windows):** Habilite **Iniciar com o Windows** se você é um jogador diário e quer o app pronto assim que ligar o PC.\n* **Ação de Fechamento:** Defina se o app deve ser encerrado ou minimizado na bandeja ao fechar a janela.\n* **Ajustes de Overlay:** Na opção \"Ajustar notificações no jogo\", uma tela de teste se abrirá. **Arraste o balão de texto pelo Foxhole** para a posição onde ele te incomode menos e depois clique em *Salvar Posições*.\n\n### 💡 Dicas Importantes\n* O Overlay é invisível para ferramentas de captura de tela normais, então seu stream permanecerá limpo se configurado corretamente!\n",
        "tutorial.stockpile.title": "Guia: Stockpile",
        "tutorial.stockpile.content": "# 📦 Stockpile (Inventário)\n\n### 🎯 Descrição\nO **Stockpile** sincroniza automaticamente seu inventário visual no jogo com a API global da coalizão. Isso permite que seus aliados vejam exatamente quais suprimentos (BMats, RMats, veículos) estão guardados e disponíveis.\n\n### ⚙️ Modo de Uso\n1. **No jogo:** Vá até um porto ou base, abra a aba do seu Stockpile particular e clique no ícone de percevejo (`Pin`) para afixá-lo no mapa do jogo.\n2. **No App:** A ferramenta encontrará instantaneamente o arquivo `_MapData.sav` no seu disco local.\n3. Clique em **Iniciar envio**.\n4. **Pronto!** O App agora fica observando o arquivo silenciosamente e faz o envio (upload) de qualquer variação diretamente para a API.\n\n### 💡 Dicas Importantes\n* Se a sincronização parar, certifique-se de que o Stockpile no mapa do Foxhole ainda está `afixado`.\n* Você pode visualizar o resumo do que você acabou de enviar diretamente no gráfico da tela inicial do Stockpile.\n",
        "tutorial.notificacoes.title": "Guia: Notificações",
        "tutorial.notificacoes.content": "# 🔔 Notificações e Timers\n\n### 🎯 Descrição\nVocê já perdeu o acesso a um veículo porque esqueceu de renovar o Squadlock? Esta ferramenta é o seu lembrete sonoro e visual para impedir que isso aconteça.\n\n### ⚙️ Modo de Uso\n1. Assim que travar o veículo (*Squadlock*) dentro do jogo, clique em **Ativar** no App.\n2. Um timer cravado de **30 minutos** iniciará silenciosamente.\n3. Ao atingir o fim da contagem, você ouvirá um alarme claro.\n4. Se o **Overlay** estiver ativado nas configurações, dois botões virtuais flutuarão na tela do jogo: **Resetar** (reinicia por +30 min) e **Terminar**.\n\n### 💡 Dicas Importantes\n* Mantenha o Foxhole em Modo Janela (Windowed Fullscreen) para garantir que as notificações do Overlay apareçam sempre no topo sem conflitos.\n",
        "tutorial.item_search.title": "Guia: Buscar Item",
        "tutorial.item_search.content": "# 🔍 Buscar Item Global\n\n### 🎯 Descrição\nO buscador salva a vida de quem está operando na frente de batalha e precisa de suprimentos específicos com urgência, como granadas antitanque, rádios, ou caixas de BMat.\n\n### ⚙️ Modo de Uso\n1. Clique na caixa de texto central e comece a digitar o nome original do item em inglês (ex: `12.7mm`).\n2. O sistema de autocomplete filtrará as melhores aproximações. Selecione o item correto.\n3. A lista se expandirá exibindo uma contagem global.\n4. Expanda a visualização e descubra exatamente **em qual base** e **em qual região** os itens estão guardados.\n\n### 💡 Dicas Importantes\n* Tente buscar pelo termo geral do armamento caso não ache pelo nome específico.\n* As informações baseiam-se em quem possui o aplicativo e escaneia os Stockpiles na região. A precisão depende do uso em time!\n",
        "tutorial.identify_item.title": "Guia: Identificador",
        "tutorial.identify_item.content": "# 👁️ Scanner de Ícones\n\n### 🎯 Descrição\nO **Identificar Item** usa Visão Computacional (OpenCV) avançada para tentar entender prints e recortes que você faz. Excelente caso você bata o olho em uma caixa estranha e não lembre o nome para buscar.\n\n### ⚙️ Modo de Uso\n1. Salve uma pequena imagem ou screenshot recortado de um ícone do Foxhole (ex: recortes com a Ferramenta de Captura do Windows).\n2. Clique em **Selecionar imagem** e carregue o arquivo.\n3. O App comparará cada pixel de milhares de ícones do Foxhole registrados na base de dados.\n4. Você receberá um *Top 3* dos ícones mais parecidos.\n\n### 💡 Dicas Importantes\n* O recorte precisa ser bem alinhado ao ícone para a OpenCV gerar o maior \"Score\" de aproximação possível. Se o score for baixo (ex: menor que 0.5), recorte a foto mais perto das bordas e tente novamente!\n",
        "tutorial.production_calculator.title": "Guia: Calculadora",
        "tutorial.production_calculator.content": "# 🏭 Calculadora de Produção\n\n### 🎯 Descrição\nFerramenta robusta para planejadores logísticos. Facilite os cálculos mentais desgastantes de *Basic Materials*, *Explosive Materials*, entre outros, na hora de fechar as filas da fábrica ou da MPF (Mass Production Factory).\n\n### ⚙️ Modo de Uso\n1. **Fábrica Simples ou MPF:** Selecione na parte superior se você quer enviar itens soltos ou caixas grandes com desconto.\n2. Navegue pelos painéis da direita para escolher entre *Itens Neutros*, *Wardens* ou *Coloniais*.\n3. Clique uma vez para adicionar 1 pedido na fila. (Segure **SHIFT** e clique para preencher a fila inteira com aquele item de uma só vez!).\n4. A lista da esquerda será atualizada.\n\n### 💡 Dicas Importantes\n* Na MPF, a taxa de **Desconto Progressivo** é aplicada aos totais de custo automaticamente. O sumário final no rodapé dirá exatamente com quantos Mats você tem que chegar de caminhão!\n* Clique com o **botão direito** num item já na fila da esquerda para removê-lo caso tenha errado a conta.\n",
        "tutorial.time_task.title": "Guia: TimeTask",
        "tutorial.time_task.content": "# ⏱️ TimeTask (Gravação de Macros)\n\n### 🎯 Descrição\nO **TimeTask** é um poderoso gravador de movimentos precisos. Ao contrário de um clicker comum que só repete uma única tecla, ele memoriza movimentações de mouse, cliques sequenciais e delays exatos entre ações. \n\n### ⚙️ Modo de Uso\n1. Dê um nome único para sua macro e clique em **Gravar**.\n2. Uma contagem regressiva surgirá no topo do seu jogo.\n3. Comece a realizar as ações (ex: arrastar componentes da base pro caminhão, separar stacks, craftar itens da guarnição).\n4. Volte e clique em **Parar e Salvar**.\n5. Na janela de *Macros Salvas*, você pode escolher a quantidade de Repetições (se deseja fazer a rotação 10 vezes seguidas, por exemplo).\n\n### 💡 Dicas Importantes\n* Você pode aumentar ou diminuir a **Velocidade** da reprodução no painel inferior. Ideal se você achou que gravou a ação de forma muito \"lenta\" e quer que o bot faça mais rápido!\n* Para parar de reproduzir de forma forçada antes de terminar todas as repetições, basta apertar a tecla **Esc**.\n",
        "startup.tips.title": "Bem-vindo!",
        "startup.tips.content": "## 🚀 Novidades e Tutoriais\n\nBem-vindo à nova versão do **GG Coalition**! \n\nAgora o aplicativo conta com um sistema de **Ajuda Integrada** em todas as telas:\n* Clique no botão **❓ (Ajuda)** localizado no canto superior direito de qualquer página.\n* Você terá acesso instantâneo a dicas exclusivas, um passo a passo completo, e os atalhos ideais para a ferramenta que você está usando no momento!\n\nFique de olho nas **Notas de Atualização** logo em seguida para ver o que mudou na versão mais recente.\n"
    },
    "en": {
        "tutorial.inicio.title": "Guide: Home",
        "tutorial.inicio.content": "# 🏠 Home\n\n### 🎯 Description\nThe **Home** screen is your central command dashboard. It gathers all crucial information about the game execution and main modules in a single unified view. Ideal for quickly checking status without losing focus on what matters.\n\n### ⚙️ How to Use\n1. **View Status:** The top panel clearly shows if *Foxhole* is open and for how long it has been running.\n2. **Integrated Chat:** Talk live with other players using the bottom tabs. You can navigate between *Logistics*, *Faci*, or *Global* chats. The text field supports automatic emojis!\n3. **Sidebar Menu:** Click the `☰` icon in the top left corner to instantly access all other automation and search tools.\n\n### 💡 Important Tips\n* Always check if your status tab points to **\"Active User\"** to ensure you are properly logged in via Steam.\n* Use the quick shortcuts in the bottom cards to quickly open the Stockpile or Production Calculator.\n",
        "tutorial.chat.title": "Guide: Chat",
        "tutorial.chat.content": "# Chat\n\n### Description\nUse the integrated chat to follow coalition rooms, see online players, send quick emojis or GIF links, and receive mention alerts while you work in other tools.\n\n### How to Use\n1. Connect with your local Steam profile.\n2. Select a room from the room list.\n3. Type a message, use quick emojis, or send a GIF URL.\n4. Type `@` to mention online users from the suggestion bar.\n\n### Tips\n* Mention overlays and sounds can be changed in Settings or Notifications.\n* GIF previews render directly in the message list when the URL points to an image.",
        "tutorial.ferramentas.title": "Guide: Auto Clicker",
        "tutorial.ferramentas.content": "# Auto Clicker\n\n### Overview\nThis page controls the main Foxhole automations. Use Capture Foxhole while the game is open to register the game window and the virtual point where clicks will be sent. The hold modes are designed to work in the background whenever possible without stealing focus.\n\n### Modes\n* Auto Clicker: uses the main hotkey, F3 by default, to click the selected mouse button every 0.3s.\n* Hold Shift: when enabled, Shift is only sent with Auto Clicker while you physically hold Shift.\n* W Hold: uses the pilot hotkey, F4 by default, to hold W. Holding S pauses W; releasing S resumes it. Esc or the same hotkey stops the mode.\n* W double-tap: when enabled, two quick W taps start W Hold.\n* Move-Click F2: holds left mouse at the captured point in the background. Press F2 again or Esc to release.\n* Right Hold: F9 by default, holds right mouse in the background. Press F9 again or Esc to release.\n* Right double-click: disabled by default; when enabled, two quick right clicks start Right Hold.\n* Artillery: F7 by default, sends R and left click at a steady pace. Esc or right click stops it.\n* Fixed double-click: uses the configured key for fast clicks and supports slots 1 to 4.\n\n### Overlay\nThe overlay shows only the active mode, a short hint, and the items enabled in settings. You can show profile, target, notifications, and change color. The panel also appears while F2, W Hold, or Right Hold are active.\n\n### Tips\n* Capture Foxhole again if the game restarts or clicks go to the wrong spot.\n* Avoid using the same key for two modes.\n* If a mode feels stuck, press Esc to release active holds.",
        "tutorial.configuracoes.title": "Guide: Settings",
        "tutorial.configuracoes.content": "# ⚙️ Settings\n\n### 🎯 Description\nPersonalize your **GG Coalition** experience with fine adjustments to the application and on-screen notifications (Overlay). Make it look the way you prefer with custom colors.\n\n### ⚙️ How to Use\n* **Sound Effects:** Enable or disable the beep that plays when a timer ends or when someone mentions you in chat.\n* **System (Windows):** Enable **Start with Windows** if you're a daily player and want the app ready as soon as you turn on the PC.\n* **Close Action:** Define whether the app should be closed or minimized to the tray when you close the window.\n* **Overlay Adjustments:** Under \"Adjust notifications in-game\", a test screen will open. **Drag the text bubble across Foxhole** to the position where it bothers you the least and then click *Save Positions*.\n\n### 💡 Important Tips\n* The Overlay is invisible to normal screen capture tools, so your stream will remain clean if set up properly!\n",
        "tutorial.stockpile.title": "Guide: Stockpile",
        "tutorial.stockpile.content": "# 📦 Stockpile (Inventory)\n\n### 🎯 Description\nThe **Stockpile** automatically synchronizes your in-game visual inventory with the global coalition API. This allows your allies to see exactly what supplies (BMats, RMats, vehicles) are stored and available.\n\n### ⚙️ How to Use\n1. **In-game:** Go to a seaport or storage depot, open your private Stockpile tab, and click the `Pin` icon to pin it to the game map.\n2. **In the App:** The tool will instantly find the `_MapData.sav` file on your local disk.\n3. Click **Start Upload**.\n4. **Done!** The App will now silently watch the file and upload any changes directly to the API.\n\n### 💡 Important Tips\n* If synchronization stops, make sure the Stockpile on the Foxhole map is still `Pinned`.\n* You can view a summary of what you just uploaded directly on the chart on the Stockpile home screen.\n",
        "tutorial.notificacoes.title": "Guide: Notifications",
        "tutorial.notificacoes.content": "# 🔔 Notifications and Timers\n\n### 🎯 Description\nHave you ever lost access to a vehicle because you forgot to renew the Squadlock? This tool is your audible and visual reminder to prevent that from happening.\n\n### ⚙️ How to Use\n1. As soon as you lock the vehicle (*Squadlock*) in the game, click **Activate** in the App.\n2. A strict **30-minute** timer will start silently.\n3. When the countdown ends, you will hear a clear alarm.\n4. If the **Overlay** is enabled in settings, two virtual buttons will float on your game screen: **Reset** (restarts for +30 min) and **Finish**.\n\n### 💡 Important Tips\n* Keep Foxhole in Windowed Fullscreen Mode to ensure Overlay notifications always appear on top without conflicts.\n",
        "tutorial.item_search.title": "Guide: Item Search",
        "tutorial.item_search.content": "# 🔍 Global Item Search\n\n### 🎯 Description\nThe search engine saves the life of those operating on the front lines who need specific supplies urgently, such as anti-tank grenades, radios, or BMat crates.\n\n### ⚙️ How to Use\n1. Click the central text box and start typing the original English name of the item (e.g., `12.7mm`).\n2. The autocomplete system will filter the best matches. Select the correct item.\n3. The list will expand showing a global count.\n4. Expand the view to find out exactly **in which base** and **in which region** the items are stored.\n\n### 💡 Important Tips\n* Try searching by the general weapon term if you can't find it by the specific name.\n* The information is based on who has the application and scans Stockpiles in the region. Accuracy depends on teamwork!\n",
        "tutorial.identify_item.title": "Guide: Identifier",
        "tutorial.identify_item.content": "# 👁️ Icon Scanner\n\n### 🎯 Description\n**Identify Item** uses advanced Computer Vision (OpenCV) to try to understand screenshots and clippings you make. Excellent for when you see a strange crate and can't remember its name to search for it.\n\n### ⚙️ How to Use\n1. Save a small image or cropped screenshot of a Foxhole icon (e.g., clippings with the Windows Snipping Tool).\n2. Click **Select image** and load the file.\n3. The App will compare every pixel against thousands of recorded Foxhole icons in the database.\n4. You will receive a *Top 3* of the most similar icons.\n\n### 💡 Important Tips\n* The clipping needs to be well-aligned with the icon for OpenCV to generate the highest possible approximation \"Score\". If the score is low (e.g., less than 0.5), crop the photo closer to the edges and try again!\n",
        "tutorial.production_calculator.title": "Guide: Calculator",
        "tutorial.production_calculator.content": "# 🏭 Production Calculator\n\n### 🎯 Description\nA robust tool for logistics planners. Make exhausting mental calculations for *Basic Materials*, *Explosive Materials*, among others, easier when closing queues at the Factory or MPF (Mass Production Factory).\n\n### ⚙️ How to Use\n1. **Standard Factory or MPF:** Select at the top whether you want to order loose items or large crates with a discount.\n2. Navigate through the right panels to choose between *Neutral*, *Warden*, or *Colonial* items.\n3. Click once to add 1 order to the queue. (Hold **SHIFT** and click to fill the entire queue with that item at once!).\n4. The left list will be updated.\n\n### 💡 Important Tips\n* In the MPF, the **Progressive Discount** rate is applied to the total costs automatically. The final summary at the footer will tell you exactly how many Mats you need to bring with your truck!\n* **Right-click** an item already in the left queue to remove it if you made a mistake.\n",
        "tutorial.time_task.title": "Guide: TimeTask",
        "tutorial.time_task.content": "# ⏱️ TimeTask (Macro Recording)\n\n### 🎯 Description\n**TimeTask** is a powerful recorder for precise movements. Unlike a common clicker that only repeats a single key, it memorizes mouse movements, sequential clicks, and exact delays between actions.\n\n### ⚙️ How to Use\n1. Give your macro a unique name and click **Record**.\n2. A countdown will appear at the top of your game.\n3. Start performing the actions (e.g., dragging components from the base to the truck, splitting stacks, crafting garrison items).\n4. Go back and click **Stop and Save**.\n5. In the *Saved Macros* window, you can choose the number of Repetitions (if you want to do the rotation 10 times in a row, for example).\n\n### 💡 Important Tips\n* You can increase or decrease the playback **Speed** in the bottom panel. Ideal if you felt you recorded the action too \"slowly\" and want the bot to do it faster!\n* To force stop playback before finishing all repetitions, just press the **Esc** key.\n",
        "startup.tips.title": "Welcome!",
        "startup.tips.content": "## 🚀 What's New & Tutorials\n\nWelcome to the new version of **GG Coalition**!\n\nThe application now features an **Integrated Help** system on all screens:\n* Click the **❓ (Help)** button located in the top right corner of any page.\n* You will have instant access to exclusive tips, a complete step-by-step guide, and the ideal shortcuts for the tool you are currently using!\n\nKeep an eye on the **Release Notes** right after this to see what changed in the latest version.\n"
    },
    "es": {
        "tutorial.inicio.title": "Guía: Inicio",
        "tutorial.inicio.content": "# 🏠 Inicio\n\n### 🎯 Descripción\nLa pantalla de **Inicio** es tu panel de comando central. Reúne toda la información crucial sobre la ejecución del juego y los módulos principales en una vista unificada. Ideal para revisar rápidamente el estado sin perder el foco en lo importante.\n\n### ⚙️ Modo de Uso\n1. **Ver Estado:** El panel superior muestra claramente si *Foxhole* está abierto y cuánto tiempo lleva ejecutándose.\n2. **Chat Integrado:** Habla en vivo con otros jugadores usando las pestañas inferiores. Puedes navegar entre los chats de *Logística*, *Faci* o *Global*. ¡El campo de texto soporta emojis automáticos!\n3. **Menú Lateral:** Haz clic en el ícono `☰` en la esquina superior izquierda para acceder instantáneamente a todas las demás herramientas de automatización y búsqueda.\n\n### 💡 Consejos Importantes\n* Verifica siempre que tu pestaña de estado indique **\"Usuario Activo\"** para asegurarte de estar correctamente conectado a través de Steam.\n* Usa los atajos rápidos en las tarjetas inferiores para abrir rápidamente el Stockpile o la Calculadora de Producción.\n",
        "tutorial.chat.title": "Guía: Chat",
        "tutorial.chat.content": "# Chat\n\n### Descripción\nUsa el chat integrado para seguir salas de la coalición, ver jugadores en línea, enviar emojis rápidos o enlaces GIF, y recibir alertas de mención mientras usas otras herramientas.\n\n### Cómo usar\n1. Conecta con tu perfil local de Steam.\n2. Elige una sala en la lista.\n3. Escribe un mensaje, usa emojis rápidos o envía una URL de GIF.\n4. Escribe `@` para mencionar usuarios en línea desde la barra de sugerencias.\n\n### Consejos\n* Los overlays y sonidos de mención se ajustan en Configuración o Notificaciones.\n* Las vistas previas de GIF aparecen directamente en la lista cuando la URL apunta a una imagen.",
        "tutorial.ferramentas.title": "Guía: Auto Clicker",
        "tutorial.ferramentas.content": "# Auto Clicker\n\n### Vista general\nEsta pantalla controla las automatizaciones principales de Foxhole. Usa Capturar Foxhole con el juego abierto para registrar la ventana y el punto virtual donde se enviarán los clics. Los modos están diseñados para funcionar en segundo plano siempre que sea posible, sin quitar el foco del juego.\n\n### Modos\n* Auto Clicker: usa la tecla de acceso rápido principal, por defecto F3, para hacer clic en el botón elegido cada 0.3s.\n* Mantener Shift: cuando está activo, Shift solo se envía con Auto Clicker si mantienes Shift físicamente.\n* W Hold: usa la tecla de acceso rápido de piloto, por defecto F4, para mantener W. Mantener S pausa W; soltar S lo reanuda. Esc o la misma tecla detiene el modo.\n* Doble toque W: cuando está activo, dos toques rápidos en W inician W Hold.\n* Move-Click F2: mantiene el botón izquierdo en el punto capturado en segundo plano. Pulsa F2 otra vez o Esc para soltar.\n* Right Hold: por defecto F9, mantiene el botón derecho en segundo plano. Pulsa F9 otra vez o Esc para soltar.\n* Doble clic derecho: viene desactivado por defecto; cuando se activa, dos clics derechos rápidos inician Right Hold.\n* Artillería: por defecto F7, envía R y clic izquierdo a ritmo constante. Esc o clic derecho lo detiene.\n* Doble fijo: usa la tecla configurada para clics rápidos y soporta ranuras del 1 al 4.\n\n### Overlay\nEl overlay muestra solo el modo activo, una pista corta y los elementos habilitados en configuración. Puedes mostrar perfil, objetivo, notificación y cambiar color. El panel también aparece mientras F2, W Hold o Right Hold estén activos.\n\n### Consejos\n* Captura Foxhole otra vez si el juego se reinicia o los clics van al lugar incorrecto.\n* Evita usar la misma tecla para dos modos.\n* Si un modo parece trabado, pulsa Esc para soltar los holds activos.",
        "tutorial.configuracoes.title": "Guía: Configuración",
        "tutorial.configuracoes.content": "# ⚙️ Configuración\n\n### 🎯 Descripción\nPersonaliza tu experiencia de **GG Coalition** con ajustes finos en la aplicación y en las notificaciones en pantalla (Overlay). Haz que se vea como prefieras con colores personalizados.\n\n### ⚙️ Modo de Uso\n* **Efectos de Sonido:** Activa o desactiva el pitido que suena cuando termina un temporizador o cuando alguien te menciona en el chat.\n* **Sistema (Windows):** Habilita **Iniciar con Windows** si eres un jugador diario y quieres la aplicación lista tan pronto como enciendas la PC.\n* **Acción de Cierre:** Define si la aplicación debe cerrarse o minimizarse en la bandeja del sistema al cerrar la ventana.\n* **Ajustes de Overlay:** En la opción \"Ajustar notificaciones en el juego\", se abrirá una pantalla de prueba. **Arrastra el globo de texto por Foxhole** hasta la posición donde menos te moleste y luego haz clic en *Guardar Posiciones*.\n\n### 💡 Consejos Importantes\n* El Overlay es invisible para las herramientas normales de captura de pantalla, ¡así que tu transmisión se mantendrá limpia si está bien configurado!\n",
        "tutorial.stockpile.title": "Guía: Stockpile",
        "tutorial.stockpile.content": "# 📦 Stockpile (Inventario)\n\n### 🎯 Descripción\nEl **Stockpile** sincroniza automáticamente tu inventario visual en el juego con la API global de la coalición. Esto permite que tus aliados vean exactamente qué suministros (BMats, RMats, vehículos) están almacenados y disponibles.\n\n### ⚙️ Modo de Uso\n1. **En el juego:** Ve a un puerto o base, abre la pestaña de tu Stockpile privado y haz clic en el ícono de la chincheta (`Pin`) para fijarlo en el mapa del juego.\n2. **En la Aplicación:** La herramienta encontrará instantáneamente el archivo `_MapData.sav` en tu disco local.\n3. Haz clic en **Iniciar envío**.\n4. **¡Listo!** La Aplicación ahora observará silenciosamente el archivo y subirá cualquier cambio directamente a la API.\n\n### 💡 Consejos Importantes\n* Si la sincronización se detiene, asegúrate de que el Stockpile en el mapa de Foxhole siga estando `Fijado`.\n* Puedes ver un resumen de lo que acabas de subir directamente en el gráfico de la pantalla principal de Stockpile.\n",
        "tutorial.notificacoes.title": "Guía: Notificaciones",
        "tutorial.notificacoes.content": "# 🔔 Notificaciones y Temporizadores\n\n### 🎯 Descripción\n¿Alguna vez perdiste acceso a un vehículo porque olvidaste renovar el Squadlock? Esta herramienta es tu recordatorio sonoro y visual para evitar que eso suceda.\n\n### ⚙️ Modo de Uso\n1. Tan pronto como bloquees el vehículo (*Squadlock*) en el juego, haz clic en **Activar** en la App.\n2. Un temporizador estricto de **30 minutos** comenzará silenciosamente.\n3. Al finalizar la cuenta regresiva, escucharás una alarma clara.\n4. Si el **Overlay** está activado en la configuración, dos botones virtuales flotarán en la pantalla de tu juego: **Reiniciar** (reinicia por +30 min) y **Terminar**.\n\n### 💡 Consejos Importantes\n* Mantén Foxhole en Modo Ventana Sin Bordes (Windowed Fullscreen) para garantizar que las notificaciones del Overlay aparezcan siempre por encima sin conflictos.\n",
        "tutorial.item_search.title": "Guía: Buscar Artículo",
        "tutorial.item_search.content": "# 🔍 Búsqueda Global de Artículos\n\n### 🎯 Descripción\nEl buscador salva la vida de aquellos que operan en el frente de batalla y necesitan suministros específicos con urgencia, como granadas antitanque, radios o cajas de BMat.\n\n### ⚙️ Modo de Uso\n1. Haz clic en la caja de texto central y comienza a escribir el nombre original del artículo en inglés (ej: `12.7mm`).\n2. El sistema de autocompletar filtrará las mejores coincidencias. Selecciona el artículo correcto.\n3. La lista se expandirá mostrando un conteo global.\n4. Expande la vista para descubrir exactamente **en qué base** y **en qué región** están almacenados los artículos.\n\n### 💡 Consejos Importantes\n* Intenta buscar por el término general del arma si no puedes encontrarlo por el nombre específico.\n* La información se basa en quién tiene la aplicación y escanea los Stockpiles en la región. ¡La precisión depende del uso en equipo!\n",
        "tutorial.identify_item.title": "Guía: Identificador",
        "tutorial.identify_item.content": "# 👁️ Escáner de Íconos\n\n### 🎯 Descripción\nEl **Identificar Artículo** usa Visión por Computadora (OpenCV) avanzada para intentar entender las capturas de pantalla y recortes que haces. Excelente para cuando ves una caja extraña y no recuerdas su nombre para buscarla.\n\n### ⚙️ Modo de Uso\n1. Guarda una pequeña imagen o captura de pantalla recortada de un ícono de Foxhole (ej: recortes con la Herramienta de Recortes de Windows).\n2. Haz clic en **Seleccionar imagen** y carga el archivo.\n3. La App comparará cada píxel con miles de íconos de Foxhole registrados en la base de datos.\n4. Recibirás un *Top 3* de los íconos más similares.\n\n### 💡 Consejos Importantes\n* El recorte debe estar bien alineado con el ícono para que OpenCV genere la mayor \"Puntuación\" de aproximación posible. Si la puntuación es baja (ej: menor a 0.5), recorta la foto más cerca de los bordes e inténtalo de nuevo.\n",
        "tutorial.production_calculator.title": "Guía: Calculadora",
        "tutorial.production_calculator.content": "# 🏭 Calculadora de Producción\n\n### 🎯 Descripción\nUna herramienta robusta para planificadores de logística. Facilita los cálculos mentales agotadores para *Materiales Básicos*, *Materiales Explosivos*, entre otros, a la hora de cerrar colas en la Fábrica o en la MPF (Fábrica de Producción Masiva).\n\n### ⚙️ Modo de Uso\n1. **Fábrica Normal o MPF:** Selecciona en la parte superior si deseas pedir artículos sueltos o cajas grandes con descuento.\n2. Navega por los paneles derechos para elegir entre artículos *Neutrales*, *Wardens* o *Coloniales*.\n3. Haz clic una vez para agregar 1 pedido a la cola. (¡Mantén presionado **SHIFT** y haz clic para llenar toda la cola con ese artículo a la vez!).\n4. La lista de la izquierda se actualizará.\n\n### 💡 Consejos Importantes\n* En la MPF, la tasa de **Descuento Progresivo** se aplica a los costos totales automáticamente. ¡El resumen final en el pie de página te dirá exactamente cuántos Materiales debes llevar con tu camión!\n* Haz **clic derecho** en un artículo que ya esté en la cola de la izquierda para eliminarlo si cometiste un error.\n",
        "tutorial.time_task.title": "Guía: TimeTask",
        "tutorial.time_task.content": "# ⏱️ TimeTask (Grabación de Macros)\n\n### 🎯 Descripción\nEl **TimeTask** es un potente grabador de movimientos precisos. A diferencia de un clicker común que solo repite una sola tecla, memoriza movimientos del mouse, clics secuenciales y retrasos exactos entre acciones.\n\n### ⚙️ Modo de Uso\n1. Dale a tu macro un nombre único y haz clic en **Grabar**.\n2. Aparecerá una cuenta regresiva en la parte superior de tu juego.\n3. Comienza a realizar las acciones (ej: arrastrar componentes de la base al camión, separar pilas, fabricar artículos de guarnición).\n4. Vuelve y haz clic en **Detener y Guardar**.\n5. En la ventana de *Macros Guardadas*, puedes elegir el número de Repeticiones (si deseas hacer la rotación 10 veces seguidas, por ejemplo).\n\n### 💡 Consejos Importantes\n* Puedes aumentar o disminuir la **Velocidad** de reproducción en el panel inferior. ¡Ideal si sentiste que grabaste la acción de manera muy \"lenta\" y quieres que el bot lo haga más rápido!\n* Para forzar la detención de la reproducción antes de terminar todas las repeticiones, simplemente presiona la tecla **Esc**.\n",
        "startup.tips.title": "¡Bienvenido!",
        "startup.tips.content": "## 🚀 Novedades y Tutoriales\n\n¡Bienvenido a la nueva versión de **GG Coalition**!\n\nLa aplicación ahora cuenta con un sistema de **Ayuda Integrada** en todas las pantallas:\n* Haz clic en el botón **❓ (Ayuda)** ubicado en la esquina superior derecha de cualquier página.\n* ¡Tendrás acceso instantáneo a consejos exclusivos, una guía completa paso a paso y los atajos ideales para la herramienta que estás usando actualmente!\n\nMantente atento a las **Notas de la Versión** a continuación para ver qué cambió en la última actualización.\n"
    },
    "fr": {
        "tutorial.inicio.title": "Guide : Accueil",
        "tutorial.inicio.content": "# 🏠 Accueil\n\n### 🎯 Description\nL'écran d'**Accueil** est votre tableau de bord de commande central. Il rassemble toutes les informations cruciales sur l'exécution du jeu et les modules principaux en une seule vue unifiée. Idéal pour vérifier rapidement le statut sans perdre de vue l'essentiel.\n\n### ⚙️ Mode d'emploi\n1. **Voir le Statut :** Le panneau supérieur indique clairement si *Foxhole* est ouvert et depuis combien de temps il fonctionne.\n2. **Chat Intégré :** Parlez en direct avec d'autres joueurs en utilisant les onglets inférieurs. Vous pouvez naviguer entre les chats *Logistique*, *Faci* ou *Global*. Le champ de texte prend en charge les émojis automatiques !\n3. **Menu Latéral :** Cliquez sur l'icône `☰` dans le coin supérieur gauche pour accéder instantanément à tous les autres outils d'automatisation et de recherche.\n\n### 💡 Conseils Importants\n* Vérifiez toujours si votre onglet de statut indique **\"Utilisateur Activo\"** pour vous assurer que vous êtes correctement connecté via Steam.\n* Utilisez les raccourcis rapides dans les cartes inférieures pour ouvrir rapidement le Stockpile ou la Calculatrice de Production.\n",
        "tutorial.chat.title": "Guide : Chat",
        "tutorial.chat.content": "# Chat\n\n### Description\nUtilisez le chat intégré pour suivre les salons de la coalition, voir les joueurs en ligne, envoyer des émojis rapides ou des liens GIF, et recevoir des alertes de mention tout en utilisant d'autres outils.\n\n### Comment utiliser\n1. Connectez-vous avec votre profil Steam local.\n2. Choisissez un salon dans la liste.\n3. Tapez un message, utilisez des émojis rapides ou envoyez une URL de GIF.\n4. Tapez `@` pour mentionner les utilisateurs en ligne depuis la barre de suggestions.\n\n### Conseils\n* Les overlays et les sons de mention peuvent être ajustés dans Paramètres ou Notifications.\n* Les aperçus de GIF s'affichent directement dans la liste lorsque l'URL pointe vers une image.",
        "tutorial.ferramentas.title": "Guide : Auto Clicker",
        "tutorial.ferramentas.content": "# Auto Clicker\n\n### Aperçu\nCette page contrôle les principales automatisations de Foxhole. Utilisez Capturer Foxhole avec le jeu ouvert pour enregistrer la fenêtre et le point virtuel où les clics seront envoyés. Les modes de maintien sont conçus pour fonctionner en arrière-plan chaque fois que possible, sans voler le focus du jeu.\n\n### Modes\n* Auto Clicker : utilise le raccourci principal, F3 par défaut, pour cliquer sur le bouton choisi toutes les 0.3s.\n* Maintenir Shift : lorsqu'il est activé, Shift n'est envoyé avec l'Auto Clicker que si vous maintenez physiquement Shift.\n* W Hold : utilise le raccourci du pilote, F4 par défaut, pour maintenir W. Maintenir S met W en pause ; relâcher S le reprend. Échap ou le même raccourci arrête le mode.\n* Double appui W : lorsqu'il est activé, deux appuis rapides sur W démarrent W Hold.\n* Move-Click F2 : maintient le clic gauche au point capturé en arrière-plan. Appuyez à nouveau sur F2 ou sur Échap pour relâcher.\n* Right Hold : par défaut F9, maintient le clic droit en arrière-plan. Appuyez à nouveau sur F9 ou sur Échap pour relâcher.\n* Double clic droit : désactivé par défaut ; lorsqu'il est activé, deux clics droits rapides démarrent Right Hold.\n* Artillerie : par défaut F7, envoie R et un clic gauche à un rythme régulier. Échap ou un clic droit l'arrête.\n* Double fixe : utilise la touche configurée pour des clics rapides et prend en charge les emplacements 1 à 4.\n\n### Overlay\nL'overlay n'affiche que le mode actif, un petit conseil et les éléments activés dans les paramètres. Vous pouvez afficher le profil, la cible, les notifications et changer de couleur. Le panneau apparaît également lorsque F2, W Hold ou Right Hold sont actifs.\n\n### Conseils\n* Capturez Foxhole à nouveau si le jeu redémarre ou si les clics vont au mauvais endroit.\n* Évitez d'utiliser la même touche pour deux modes.\n* Si un mode semble bloqué, appuyez sur Échap pour relâcher tous les maintiens actifs.",
        "tutorial.configuracoes.title": "Guide : Paramètres",
        "tutorial.configuracoes.content": "# ⚙️ Paramètres\n\n### 🎯 Description\nPersonnalisez votre expérience **GG Coalition** avec des ajustements précis de l'application et des notifications à l'écran (Overlay). Donnez-lui l'apparence que vous préférez avec des couleurs personnalisées.\n\n### ⚙️ Mode d'emploi\n* **Effets Sonores :** Activez ou désactivez le bip qui retentit lorsqu'un minuteur se termine ou lorsque quelqu'un vous mentionne dans le chat.\n* **Système (Windows) :** Activez **Démarrer avec Windows** si vous êtes un joueur quotidien et que vous voulez l'application prête dès que vous allumez le PC.\n* **Action de Fermeture :** Définissez si l'application doit être fermée ou minimisée dans la barre d'état système lors de la fermeture de la fenêtre.\n* **Ajustements de l'Overlay :** Sous l'option \"Ajustar les notifications en jeu\", un écran de test s'ouvrira. **Faites glisser la bulle de texte sur Foxhole** vers la position où elle vous dérange le moins, puis cliquez sur *Enregistrer les positions*.\n\n### 💡 Conseils Importants\n* L'Overlay est invisible pour les outils de capture d'écran normaux, donc votre stream restera propre si bien configuré !\n",
        "tutorial.stockpile.title": "Guide : Stockpile",
        "tutorial.stockpile.content": "# 📦 Stockpile (Inventaire)\n\n### 🎯 Description\nLe **Stockpile** synchronise automatiquement votre inventaire visuel en jeu avec l'API globale de la coalition. Cela permet à vos alliés de voir exactement quelles fournitures (BMats, RMats, véhicules) sont stockées et disponibles.\n\n### ⚙️ Mode d'emploi\n1. **En jeu :** Allez à un port ou une base, ouvrez l'onglet de votre Stockpile privé et cliquez sur l'icône de la punaise (`Pin`) pour l'épingler sur la carte du jeu.\n2. **Dans l'Application :** L'outil trouvera instantanément le fichier `_MapData.sav` sur votre disque local.\n3. Cliquez sur **Démarrer l'envoi**.\n4. **Terminé !** L'application observera maintenant silencieusement le fichier et téléchargera toute modification directement vers l'API.\n\n### 💡 Conseils Importants\n* Si la synchronisation s'arrête, assurez-vous que le Stockpile sur la carte de Foxhole est toujours `Épinglé`.\n* Vous pouvez afficher un résumé de ce que vous venez d'envoyer directement sur le graphique de l'écran d'accueil du Stockpile.\n",
        "tutorial.notificacoes.title": "Guide : Notifications",
        "tutorial.notificacoes.content": "# 🔔 Notifications et Minuteurs\n\n### 🎯 Description\nAvez-vous déjà perdu l'accès à un véhicule parce que vous avez oublié de renouveler le Squadlock ? Cet outil est votre rappel sonore et visuel pour éviter que cela ne se produise.\n\n### ⚙️ Mode d'emploi\n1. Dès que vous verrouillez le véhicule (*Squadlock*) dans le jeu, cliquez sur **Activer** dans l'application.\n2. Un minuteur strict de **30 minutes** commencera silencieusement.\n3. Lorsque le compte à rebours se termine, vous entendrez une alarme claire.\n4. Si l'**Overlay** est activé dans les paramètres, deux boutons virtuels flotteront sur l'écran de votre jeu : **Réinitialiser** (redémarre pour +30 min) et **Terminar**.\n\n### 💡 Conseils Importants\n* Gardez Foxhole en Mode Fenêtré Sans Bordure (Windowed Fullscreen) pour vous assurer que les notifications de l'Overlay apparaissent toujours au premier plan sans conflits.\n",
        "tutorial.item_search.title": "Guide : Chercher Article",
        "tutorial.item_search.content": "# 🔍 Recherche Globale d'Articles\n\n### 🎯 Description\nLe moteur de recherche sauve la vie de ceux qui opèrent sur la ligne de front et qui ont un besoin urgent de fournitures spécifiques, comme des grenades antichars, des radios ou des caisses de BMat.\n\n### ⚙️ Mode d'emploi\n1. Cliquez sur la zone de texte centrale et commencez à taper le nom original en anglais de l'article (ex: `12.7mm`).\n2. Le système de saisie semi-automatique filtrera les meilleures correspondances. Sélectionnez le bon article.\n3. La liste s'agrandira pour afficher un décompte global.\n4. Développez la vue pour découvrir exactement **dans quelle base** et **dans quelle région** les articles sont stockés.\n\n### 💡 Conseils Importants\n* Essayez de chercher par le terme général de l'arme si vous ne trouvez pas avec le nom spécifique.\n* Les informations sont basées sur ceux qui possèdent l'application et scannent les Stockpiles dans la région. La précision dépend de l'utilisation en équipe !\n",
        "tutorial.identify_item.title": "Guide : Identificateur",
        "tutorial.identify_item.content": "# 👁️ Scanner d'Icônes\n\n### 🎯 Description\nL'**Identifier Article** utilise une Vision par Ordinateur avancée (OpenCV) pour tenter de comprendre les captures d'écran et les découpages que vous faites. Excellent lorsque vous voyez une caisse étrange et ne vous rappelez plus de son nom pour la chercher.\n\n### ⚙️ Mode d'emploi\n1. Enregistrez une petite image ou une capture d'écran recadrée d'une icône Foxhole (ex: des coupures avec l'Outil Capture Capture de Windows).\n2. Cliquez sur **Sélectionner l'image** et chargez le fichier.\n3. L'Application comparera chaque pixel à des milliers d'icônes Foxhole enregistrées dans la base de données.\n4. Vous recevrez un *Top 3* des icônes les plus similaires.\n\n### 💡 Conseils Importants\n* Le découpage doit être bien aligné avec l'icône pour qu'OpenCV génère le « Score » d'approximation le plus élevé possible. Si le score est faible (ex: inférieur à 0.5), recadrez la photo plus près des bords et réessayez !\n",
        "tutorial.production_calculator.title": "Guide : Calculatrice",
        "tutorial.production_calculator.content": "# 🏭 Calculatrice de Production\n\n### 🎯 Description\nUn outil robuste pour les planificateurs logistiques. Facilitez les calculs mentaux épuisants pour les *Matériaux de Base*, *Matériaux Explosifs*, entre autres, lors de la fermeture des files d'attente à l'Usine ou à la MPF (Usine de Production de Masse).\n\n### ⚙️ Mode d'emploi\n1. **Usine Standard ou MPF :** Sélectionnez en haut si vous souhaitez commander des articles en vrac ou de grandes caisses avec une réduction.\n2. Naviguez à travers les panneaux de droite pour choisir entre les articles *Neutres*, *Wardens* ou *Coloniaux*.\n3. Cliquez une fois pour ajouter 1 commande à la file d'attente. (Maintenez **SHIFT** et cliquez pour remplir toute la file d'attente avec cet article en une seule fois !).\n4. La liste de gauche sera mise à jour.\n\n### 💡 Conseils Importants\n* Dans la MPF, le taux de **Remise Progressive** s'applique automatiquement aux coûts totaux. Le résumé final en bas de page vous dira exactement combien de Mats vous devez apporter avec votre camion !\n* Faites un **clic droit** sur un article déjà dans la file de gauche pour le supprimer si vous avez fait une erreur.\n",
        "tutorial.time_task.title": "Guide : TimeTask",
        "tutorial.time_task.content": "# ⏱️ TimeTask (Enregistrement de Macros)\n\n### 🎯 Description\nLe **TimeTask** est un puissant enregistreur de mouvements précis. Contrairement à un clicker commun qui ne répète qu'une seule touche, il mémorise les mouvements de la souris, les clics séquentiels et les délais exacts entre les actions.\n\n### ⚙️ Mode d'emploi\n1. Donnez un nom unique à votre macro et cliquez sur **Enregistrer**.\n2. Un compte à rebours apparaîtra en haut de votre jeu.\n3. Commencez à effectuer les actions (ex: faire glisser des composants de la base vers le camion, séparer des piles, fabriquer des articles de garnison).\n4. Revenez et cliquez sur **Arrêter et Enregistrer**.\n5. Dans la fenêtre *Macros Enregistrées*, vous pouvez choisir le nombre de Répétitions (si vous souhaitez faire la rotation 10 fois de suite, par exemple).\n\n### 💡 Conseils Importants\n* Vous pouvez augmenter ou diminuer la **Vitesse** de lecture dans le panneau inférieur. Idéal si vous avez l'impression d'avoir enregistré l'action trop « lentement » et que vous voulez que le bot le fasse plus rapidement !\n* Pour forcer l'arrêt de la lecture avant de terminer toutes les répétitions, appuyez simplement sur la touche **Échap**.\n",
        "startup.tips.title": "Bienvenue !",
        "startup.tips.content": "## 🚀 Nouveautés et Tutoriels\n\nBienvenue dans la nouvelle version de **GG Coalition** !\n\nL'application dispose désormais d'un système d'**Aide Intégrée** sur tous les écrans :\n* Cliquez sur le bouton **❓ (Aide)** situé dans le coin supérieur droit de n'importe quelle page.\n* Vous aurez un accès instantané à des conseils exclusifs, un guide étape par étape complet, et les raccourcis idéaux pour l'outil que vous utilisez actuellement !\n\nGardez un œil sur les **Notes de Version** juste après cela pour voir ce qui a changé dans la dernière mise à jour.\n"
    }
}

for lang, updates in translations.items():
    file_path = os.path.join(base_path, lang, 'translation.json')
    if os.path.exists(file_path):
        with open(file_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        for k, v in updates.items():
            if 'content' in k:
                # Reformat markdown to be less cramped
                v = v.replace("### ", "---\n## ")
                v = v.replace("\n1. ", "\n\n1. ")
                v = v.replace("\n2. ", "\n\n2. ")
                v = v.replace("\n3. ", "\n\n3. ")
                v = v.replace("\n4. ", "\n\n4. ")
                v = v.replace("\n5. ", "\n\n5. ")
                v = v.replace("\n6. ", "\n\n6. ")
                v = v.replace("\n* ", "\n\n* ")
                # Sometimes startup tips use ## instead of ###. Don't touch startup tips if it doesn't have ###, but if it has *, we spaced it out.
            data[k] = v
            
        with open(file_path, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
            
print("Done!")
